# Generated by Django 4.2.5 on 2023-09-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainchat', '0002_friend_delete_friends_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_friends', to='mainchat.friend'),
        ),
    ]
